title: Giridharan Sankar
email: giridharan.s@students.iiserpune.ac.in
description: >
  Physics student at IISER Pune. Interested in astrophysics, exoplanetary atmospheres, and star formation theory.
baseurl: ""
url: "https://giridharan-sankar.github.io"
theme: jekyll-theme-minimal
