title: Giridharan Sankar
email: giridharan.s@students.iiserpune.ac.in
description: >- # this means to ignore newlines until "baseurl:"
  Physics student at IISER Pune. Interested in astrophysics, exoplanetary atmospheres, and star formation theory.
baseurl: "" # the subpath of your site, e.g., /blog
url: "https://yourusername.github.io" # the base hostname & protocol for your site

theme: jekyll-theme-minimal
plugins:
  - jekyll-feed